### ISSUE TITLE
推荐一个 【联邦学习】 的网站外链

### ISSUE THREAD

**Issue by youngfish42** [international-explore/awesome-privacy-chinese#5]
感谢各位开发者的贡献和整理，这个仓库的资讯很有用。

我注意到网站外链部分有记录隐私相关技术的仓库，在此特地推荐一个 【联邦学习】 的网站外链
[**Awesome-Federated-Learning-on-Graph-and-Tabular-Data**](https://github.com/youngfish42/Awesome-Federated-Learning-on-Graph-and-Tabular-Data) 
该仓库一方面追踪联邦学习在图和表数据上的应用，另一方面针对联邦学习开源框架和顶刊顶会上的论文清单的整理应当是全网最新最全的。

**Comment by cuihuan** [comment]
已经增加，感谢分享
